### ISSUE TITLE
Upload and download in Chrome

### ISSUE THREAD

**Issue by hifi25nl** [SirSAC/DisPro#6]
Nice app and is working fine for internet navigation!
I am combining 2 interfaces, Ethernet and WiFi on archlinux.
However I have 2 problems:

1) Downloading in chrome is using only one interface. Tested also download from google drive with the same result.
2) Also uploading is always using one interface.

I am starting DisPro as user with this line:
DisProLinux.bin 192.168.1.5 192.168.1.6

Some more questions:
- I am using systemd network. Can you suggest an easy way to configure a socks5 at port 1080? For the moment I have added proxy with a chrome add-on ( Switchy Omega)
- Is this app supposed to run as root? Now I have set chmod --verbose 0755, chown -c root:daemon and setcap cap_net_admin,cap_net_raw=eip on the app file, but I am running it as user.

Thanks

**Comment by SirSAC** [comment]
Hello, if the protocol is UDP cant be managed by DisPro but if is TCP upload can be on second NIC but it depends the work on background that sometimes is not visible on DisPro but managed, anyway if u read all instructions u need to rename to DisPro.bin in order to work 100% correctly.

**Comment by SirSAC** [comment]
i always suggest to use root permission to prevent any issues or errors that can come over time.

**Comment by hifi25nl** [comment]
Hello,
I am testing it just now. Is working fine. Running it as root. I have only 2 problems:

1) Only from time to time access to a site give ERR_SOCKS_CONNECTION_FAILED in chrome. This with Switchy Omega. No sure if this is related to the chrome extension or DisPro. After reloading the page multiple times connection is re-established.

2) I would like to test internet speed with speedtest on command line. I have installed proxychains and tsocks.
Both are in general not working, that is only one network interface is used. What is strange is that sometime proxychains and tsocks they are working... with proxy variables never.

TSOCKS
_tsocks speedtest -s 4302_
configuration:
_server = 127.0.0.1
server_port = 1080
server_type = 5
default_user = ""
default_pass = ""_

PROXYCHAINS
_proxychains -f /etc/proxychains.conf speedtest -s 4302_
configuration:
_socks5 	127.0.0.1 1080_

WITH PROXY SYSTEM VARIABLES:
_export http_proxy='socks5://localhost:1080'
export https_proxy='socks5://localhost:1080'
export ftp_proxy='socks5://localhost:1080'
export rsync_proxy='socks5://localhost:1080'
export HTTP_PROXY='socks5://localhost:1080'
export HTTPS_PROXY='socks5://localhost:1080'
export FTP_PROXY='socks5://localhost:1080'
export RSYNC_PROXY='socks5://localhost:1080'
export all_proxy='socks5://localhost:1080'
export all_proxy='socks5://localhost:1080'
export all_proxy='socks5://localhost:1080'; speedtest -s 4302_

**Comment by hifi25nl** [comment]
I will rename it now to DisPro.bin...

**Comment by SirSAC** [comment]
Hi and sry but ur issue is unknown for me bcs i never tested on ArchLinux based.
The program work 100% on Windows and Debian based linux.
An update is in work, just i need to do alot of tests for improve stability and to be sure the new codes and changed ones are working well.
